// <auto-generated />
using System;
using CbMaker.Infrastructure.Context.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CbMaker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CbMaker.Domain.AcademicField", b =>
                {
                    b.Property<long>("AcademicFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("academifield_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcademicFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("AcademicFieldId")
                        .HasName("academifields_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "academifields_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_academifields", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.AcademicHistory", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("AcademicFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("academifield_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("DegreeId")
                        .HasMaxLength(100)
                        .HasColumnType("bigint")
                        .HasColumnName("degree_id");

                    b.Property<long?>("DegreeId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("institution_name");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("speciality");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("ExternalId")
                        .HasName("academichistories_pkey");

                    b.HasIndex("AcademicFieldId");

                    b.HasIndex("DegreeId");

                    b.HasIndex("DegreeId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex(new[] { "ExternalId" }, "academichistories_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_academic_histories", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.Degree", b =>
                {
                    b.Property<long>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("degree_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DegreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DegreeId")
                        .HasName("degrees_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "degrees_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_degrees", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.JobTitle", b =>
                {
                    b.Property<long>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("jobtitle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobTitleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("JobTitleId")
                        .HasName("jobtitles_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "jobtitles_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_job_titles", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.Language", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("AcademicFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("academifield_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ExternalId")
                        .HasName("languages_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "languages_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_languages", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.Skill", b =>
                {
                    b.Property<long>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SkillId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("SkillId")
                        .HasName("skills_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "skills_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_skills", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmed")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("email_confirmed");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("hash_password");

                    b.Property<double>("PhoneNumber")
                        .HasColumnType("float")
                        .HasColumnName("phone_number");

                    b.Property<double>("PhoneNumberConfirmed")
                        .HasColumnType("float")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "users_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_users", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.UserInfo", b =>
                {
                    b.Property<long>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("userinfo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserInfoId"));

                    b.Property<string>("AddressOne")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address_one");

                    b.Property<string>("AddressTwo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address_two");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsCitizen")
                        .HasColumnType("bit")
                        .HasColumnName("is_citizen");

                    b.Property<bool>("IsOver18")
                        .HasColumnType("bit")
                        .HasColumnName("is_over_18");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<double>("ZipCode")
                        .HasColumnType("float")
                        .HasColumnName("zip_code");

                    b.HasKey("UserInfoId")
                        .HasName("userinfo_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "userinfo_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_user_info", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.UserInfoLanguage", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("language_id");

                    b.Property<double>("Level")
                        .HasColumnType("float")
                        .HasColumnName("level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserInfoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_info_id");

                    b.HasKey("ExternalId")
                        .HasName("userinfolanguages_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "userinfolanguages_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_user_info_languages", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.UserSkill", b =>
                {
                    b.Property<long>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserSkillId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserSkillId")
                        .HasName("userskills_pkey");

                    b.ToTable("tb_user_skills", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.WorkExperience", b =>
                {
                    b.Property<long>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("work_experience_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkExperienceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("EnterpriseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("enterprise_name");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("JobTitleId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_title_id");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("responsibilities");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("WorkExperienceId")
                        .HasName("workexperience_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "workexperience_externalid_key")
                        .IsUnique();

                    b.ToTable("tb_work_experience", "dbo");
                });

            modelBuilder.Entity("CbMaker.Domain.AcademicHistory", b =>
                {
                    b.HasOne("CbMaker.Domain.AcademicField", "AcademicField")
                        .WithMany("AcademicHistories")
                        .HasForeignKey("AcademicFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbMaker.Domain.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbMaker.Domain.Degree", null)
                        .WithMany("AcademicHistories")
                        .HasForeignKey("DegreeId1");

                    b.HasOne("CbMaker.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CbMaker.Domain.User", null)
                        .WithMany("AcademicHistories")
                        .HasForeignKey("UserId1");

                    b.Navigation("AcademicField");

                    b.Navigation("Degree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CbMaker.Domain.AcademicField", b =>
                {
                    b.Navigation("AcademicHistories");
                });

            modelBuilder.Entity("CbMaker.Domain.Degree", b =>
                {
                    b.Navigation("AcademicHistories");
                });

            modelBuilder.Entity("CbMaker.Domain.User", b =>
                {
                    b.Navigation("AcademicHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
